fix: add conditional to unzip files by extension

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -10,13 +10,19 @@ source "${plugin_dir}/lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION"
 
 # Download zip file to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
-#  Extract contents of zip file into the download directory
-unzip -p "$release_file" | tar -xvf - -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
+if test -f "$release_file.zip";
+then
+    #  Extract contents of zip file into the download directory
+    unzip -p "$release_file.zip" | tar -xvf - -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
+else
+    # Extract contents of .tar.gz file into the download directory
+    tar -xvzf "$release_file.tar.gz" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
+fi
 
 # Remove the zip file since we don't need to keep it
 rm "$release_file"
